# Generated by Django 2.1 on 2018-08-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='产品名')),
                ('details', models.TextField(verbose_name='产品说明')),
                ('font', models.ImageField(upload_to='', verbose_name='产品封面')),
            ],
        ),
    ]
