# Generated by Django 2.1 on 2018-08-26 10:04

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='more_details',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='产品详细说明'),
        ),
        migrations.AlterField(
            model_name='product',
            name='font',
            field=models.ImageField(upload_to='products', verbose_name='产品封面'),
        ),
    ]
