# Generated by Django 2.1 on 2018-08-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180826_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='所用位置')),
                ('content', models.ImageField(upload_to='other', verbose_name='图片')),
            ],
        ),
    ]
