# Generated by Django 2.1 on 2018-08-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_news_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='key_word',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='关键词'),
        ),
    ]
