# Generated by Django 2.1 on 2018-08-26 11:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_news_key_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='more_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='新闻详细内容'),
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.TextField(default=None, verbose_name='新闻短内容'),
            preserve_default=False,
        ),
    ]
