# Generated by Django 2.1 on 2018-08-26 11:38

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20180826_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherRichText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='所用位置')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='内容')),
            ],
            options={
                'verbose_name_plural': '其他富文本',
                'verbose_name': '其他富文本',
            },
        ),
    ]
