# Generated by Django 2.1 on 2018-08-26 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_otherrichtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherimages',
            name='code',
            field=models.IntegerField(default=0),
        ),
    ]
