# Generated by Django 2.1 on 2018-08-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_otherimages_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherimages',
            name='code',
            field=models.IntegerField(default=0, verbose_name='编号'),
        ),
    ]
