# Generated by Django 2.1 on 2018-08-26 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20180826_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='otherrichtext',
            name='code',
            field=models.IntegerField(default=0, verbose_name='编号'),
        ),
        migrations.AddField(
            model_name='othertext',
            name='code',
            field=models.IntegerField(default=0, verbose_name='编号'),
        ),
    ]
