# Generated by Django 2.1 on 2018-08-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20180826_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherimages',
            name='code',
            field=models.IntegerField(default=0, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='otherrichtext',
            name='code',
            field=models.IntegerField(default=0, unique=True, verbose_name='编号'),
        ),
        migrations.AlterField(
            model_name='othertext',
            name='code',
            field=models.IntegerField(default=0, unique=True, verbose_name='编号'),
        ),
    ]
